const GLOBAL_SAVE = 'GLOBAL_SAVE_SYSTEM_INFO'

const HOME_SAVE = 'HOME_SAVE'

const USER_LOGOUT = 'USER_LOGOUT'
const USER_SAVE = 'USER_SAVE'

const ACTIVITY_SAVE = 'ACTIVITY_SAVE'

export {ACTIVITY_SAVE, USER_SAVE, USER_LOGOUT, HOME_SAVE, GLOBAL_SAVE}

