const GLOBAL_SAVE = 'GLOBAL_SAVE_SYSTEM_INFO'

const HOME_SAVE = 'HOME_SAVE'

const USER_SAVE = 'USER_SAVE'
const USER_IMAGE_SAVE = 'USER_IMAGE_SAVE'
const USER_IMAGE_DELETE = 'USER_IMAGE_DELETE'
const USER_PERSONINFO_SAVE = 'USER_PERSONINFO_SAVE'

const ACTIVITY_SAVE = 'ACTIVITY_SAVE'
const SAVE_VOUCHER_READ_INFO = 'SAVE_VOUCHER_READ_INFO';
const SET_HAS_VOUCHER = 'SET_HAS_VOUCHER';
const ACTIVITY_SIGN_UP_SAVE = 'ACTICITY_SIGN_UP_SAVE'
const ACTIVITY_WALLET_SAVE = 'ACTIVITY_WALLET_SAVE'
const ACTIVITY_FILL_FORM_SAVE = 'ACTIVITY_FILL_FORM_SAVE'
const ACTIVITY_CHOOSE_SAVE = 'ACTIVITY_CHOOSE_SAVE'
const ACTIVITY_MATCH_SAVE = 'ACTIVITY_MATCH_SAVE'
const ACTIVITY_DAILYQA_SAVE = 'ACTIVITY_DAILYQA_SAVE'
const ACTIVITY_APPROVE_SAVE = 'ACTIVITY_APPROVE_SAVE'
const ACTIVITY_ANALYSIS_SAVE = 'ACTIVITY_ANALYSIS_SAVE'
const ACTIVITY_BASIC_DATA_SAVE = 'ACTIVITY_BASIC_DATA_SAVE'

const MATCH_SAVE = 'MATCH_SAVE'

const CHOOSE_SAVE = 'CHOOSE_SAVE'

const RESOURCE_SAVE = 'RESOURCE_SAVE'

const MATCH_FEEDBACK_SAVE = 'MATCH_FEEDBACK_SAVE'

const PRODUCT_FEEDBACK_SAVE = 'PRODUCT_FEEDBACK_SAVE'

export {
  ACTIVITY_SAVE,
  SAVE_VOUCHER_READ_INFO,
  SET_HAS_VOUCHER,
  ACTIVITY_SIGN_UP_SAVE,
  ACTIVITY_WALLET_SAVE,
  ACTIVITY_CHOOSE_SAVE,
  ACTIVITY_MATCH_SAVE,
  ACTIVITY_FILL_FORM_SAVE,
  USER_SAVE,
  USER_IMAGE_SAVE,
  USER_IMAGE_DELETE,
  USER_PERSONINFO_SAVE,
  HOME_SAVE,
  GLOBAL_SAVE,
  RESOURCE_SAVE,
  MATCH_SAVE,
  CHOOSE_SAVE,
  ACTIVITY_DAILYQA_SAVE,
  ACTIVITY_APPROVE_SAVE,
  ACTIVITY_ANALYSIS_SAVE,
  ACTIVITY_BASIC_DATA_SAVE,
  MATCH_FEEDBACK_SAVE,
  PRODUCT_FEEDBACK_SAVE
}

