const GLOBAL_SAVE = 'GLOBAL_SAVE_SYSTEM_INFO'

const HOME_SAVE = 'HOME_SAVE'

const USER_SAVE = 'USER_SAVE'

const ACTIVITY_SAVE = 'ACTIVITY_SAVE'
const ACTIVITY_MATCH_STATE_SAVE = 'ACTIVITY_MATCH_STATE_SAVE'
const ACTIVITY_TWC_STATE_SAVE = 'ACTIVITY_TWC_STATE_SAVE'

const RESOURCE_SAVE = 'RESOURCE_SAVE'

export {ACTIVITY_SAVE,
  USER_SAVE,
  HOME_SAVE,
  GLOBAL_SAVE,
  ACTIVITY_MATCH_STATE_SAVE, ACTIVITY_TWC_STATE_SAVE,
  RESOURCE_SAVE}

